services:
  db:
    image: postgres:15
    container_name: postgres_sql_practice
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # - pg_data:/var/lib/postgresql/data
      - "./data/persistent/postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - sqlnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_sql_practice
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - "./data/persistent/pgadmin_data:/var/lib/pgadmin:rw"
    depends_on:
      - db
    networks:
      - sqlnet

volumes:
  pg_data:
  pgadmin_data:

networks:
  sqlnet:
    driver: bridge

